### ISSUE TITLE
Treasure Hunting Stage Missing Objects

### ISSUE THREAD

**Issue by insoulxiii** [Justin113D/SA2CharacterSelectPlus#10]
In Pumpkin Hill, there are many Omochao in the same exact spot, causing them all to go off at once (which is admittedly really funny), and Shovel Claw will not spawn in story mode. Same for the Hammer Gloves in Death Chamber. The lost chao won't spawn in Death Chamber either. Probably other things. Can you make it so that the Treasure Hunting stage changes are optional if you can't fix it?

**Comment by Sora-yx** [comment]
Fixed in the last version.
