### ISSUE TITLE
Game Crashing Bug in Meteor Herd, Mad Space, etc

### ISSUE THREAD

**Issue by cheatfreak47** [Justin113D/SA2CharacterSelectPlus#5]
In the event, the game turns you around while gliding, the game crashes
an easy place to reproduce this is at the top of meteor herd here:
![213610_20201123000105_1](https://user-images.githubusercontent.com/7818664/99930681-e8543180-2d1f-11eb-95b9-0cba7b29074d.png)
just jump off and fly towards the rings, past them and when you hit the boundary it crashes the game with this kind of error in the event log
```
Faulting application name: sonic2app.exe, version: 0.0.0.0, time stamp: 0x50601ae8
Faulting module name: sonic2app.exe, version: 0.0.0.0, time stamp: 0x50601ae8
Exception code: 0xc0000005
Fault offset: 0x0032b10b
Faulting process id: 0x4190
Faulting application start time: 0x01d6c14f6875787e
Faulting application path: H:\SteamLibrary\steamapps\common\Sonic Adventure 2\sonic2app.exe
Faulting module path: H:\SteamLibrary\steamapps\common\Sonic Adventure 2\sonic2app.exe
Report Id: be535342-2301-4e07-8f53-2d83286d035e

**Comment by Sora-yx** [comment]
Fixed in #9
